### ISSUE TITLE
General SSLEngine problem

### ISSUE THREAD

**Issue by J0TTaS** [f5devcentral/f5-eclipse-plugin#3]
When trying to connect to my F5 LTM 1500 (BIG-IP version **10.2.4**) I get an error related to SSL Handshake:

![generalsslerror](https://user-images.githubusercontent.com/7755448/39762331-9ac249f6-52da-11e8-9a33-273d544d2ef1.PNG)

A screenshot of the log message

![generalssl_error_eclipselog](https://user-images.githubusercontent.com/7755448/39764220-6b4a27d4-52df-11e8-89ac-6a18a83d1ce4.PNG)

And a detailed stack trace and session info from Eclipse:

**Exception Stack Trace:**

javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.wrap(Unknown Source)
	at javax.net.ssl.SSLEngine.wrap(Unknown Source)
	at com.f5.rest.common.AsynchronousSocketChannelSecure$SslHandshakeTask.doHandshake(AsynchronousSocketChannelSecure.java:738)
	at com.f5.rest.common.AsynchronousSocketChannelSecure$SslHandshakeTask.doHandshake(AsynchronousSocketChannelSecure.java:806)
	at com.f5.rest.common.AsynchronousSocketChannelSecure$SslHandshakeTask.doHandshake(AsynchronousSocketChannelSecure.java:806)
	at com.f5.rest.common.AsynchronousSocketChannelSecure$SslHandshakeTask.doHandshake(AsynchronousSocketChannelSecure.java:806)
	at com.f5.rest.common.AsynchronousSocketChannelSecure$SslHandshakeTask.access$1900(AsynchronousSocketChannelSecure.java:695)
	at com.f5.rest.common.AsynchronousSocketChannelSecure$SslHandshakeTask$2.completed(AsynchronousSocketChannelSecure.java:770)
	at com.f5.rest.common.AsynchronousSocketChannelSecure$SslHandshakeTask$2.completed(AsynchronousSocketChannelSecure.java:765)
	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.completed(Unknown Source)
	at sun.nio.ch.Iocp$EventHandlerTask.run(Unknown Source)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker$1.run(Unknown Source)
	at sun.security.ssl.Handshaker$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Unknown Source)
	at com.f5.rest.common.AsynchronousSocketChannelSecure$SslHandshakeTask.doHandshake(AsynchronousSocketChannelSecure.java:791)
	... 13 more
Caused by: java.security.cert.CertificateException: Certificates does not conform to algorithm constraints
	at sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(Unknown Source)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(Unknown Source)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(Unknown Source)
	... 21 more

**Session Data:**

eclipse.buildId=4.7.2.M20171130-0510
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es_ES
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -data file:/C:/Users/t151784/eclipse-workspace/ -product org.eclipse.epp.package.jee.product

I also attach a Wireshark trace screenshot. If it is analysed it can be seen that the SSL Handshake wasn't completed succesfully.

![generalsslerror](https://user-images.githubusercontent.com/7755448/39762563-42287b7a-52db-11e8-8422-4429297a4c04.PNG)

**Comment by rreichenbach** [comment]
TMOS versions earlier than 12.1 are not supported by the F5 plugin.  This is fairly clearly stated in the README.  It's not possible to even enhance the plugin to support older versions because it requires API's which simply never existed in earlier versions of TMOS.
